class Dummydb {
  static List category = [
    {"All": "all"},
    {"Business": "business"},
    {"Entertainment": "entertainment"},
    {"General health": "general health"},
    {"Science": "science"},
    {"Sports": "sports"},
    {"Technology": "technology"}
  ];
  static List<Map> countries = [
    {"United Arab Emirates": "ae"},
    {"Austria": "at"},
    {"Australia": "au"},
    {"Belgium": "be"},
    {"Bulgaria": "bg"},
    {"Brazil": "br"},
    {"Canada": "ca"},
    {"Switzerland": "ch"},
    {"China": "cn"},
    {"Colombia": "co"},
    {"Cuba": "cu"},
    {"Czech Republic": "cz"},
    {"Germany": "de"},
    {"Egypt": "eg"},
    {"France": "fr"},
    {"United Kingdom": "gb"},
    {"Greece": "gr"},
    {"Hong Kong": "hk"},
    {"Indonesia": "id"},
    {"Ireland": "ie"},
    {"Israel": "il"},
    {"India": "in"},
    {"Japan": "jp"},
    {"South Korea": "kr"},
    {"Lithuania": "lt"},
    {"Latvia": "lv"},
    {"Morocco": "ma"},
    {"Mexico": "mx"},
    {"Malaysia": "my"},
    {"Nigeria": "ng"},
    {"Netherlands": "nl"},
    {"Norway": "no"},
    {"New Zealand": "nz"},
    {"Philippines": "ph"},
    {"Poland": "pl"},
    {"Portugal": "pt"},
    {"Romania": "ro"},
    {"Serbia": "rs"},
    {"Russia": "ru"},
    {"Saudi Arabia": "sa"},
    {"Sweden": "se"},
    {"Singapore": "sg"},
    {"Slovakia": "sk"},
    {"Thailand": "th"},
    {"Turkey": "tr"},
    {"Taiwan": "tw"},
    {"Ukraine": "ua"},
    {"United States": "us"},
    {"Venezuela": "ve"},
    {"South Africa": "za"}
  ];
}
